# Generated by Django 5.2.4 on 2025-07-10 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('github_tokem', models.CharField(max_length=200)),
                ('repository', models.CharField(max_length=200)),
            ],
        ),
    ]
